services:
  server:
    image: c0dezer019/image2-server:${PENV:-latest}
    environment:
      - LOCAL_MODE=true
    ports:
      - "8000:8000"
    networks:
      - image2-net

  web:
    image: c0dezer019/image2-web:${PENV:-latest}
    environment:
      - NEXT_PUBLIC_IMAGE2_SERVER_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - image2-net

networks:
  image2-net:
    driver: bridge
