[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "image2"
version = "1.2.2"
description = "Convert images to colored ASCII or traditional ANSI art."
requires-python = ">=3.14"
dependencies = ["Pillow", "cairosvg"]

[project.scripts]
img2 = "image2:main"
[tool.setuptools]
py-modules = ["image2", "img2ansi", "img2ascii", "imgcommon", "imgsvg", "img2ui"]
packages = ["_img2ui_data"]

[tool.setuptools.package-data]
"_img2ui_data" = ["docker-compose.yml"]

[tool.black]
line-length = 79
target-version = ['py314']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
